"""
FastAPI Backend Server — Research Agent API v3
Answers are generated by Groq LLaMA-3 reading actual uploaded document chunks.
Falls back to improved template answers if GROQ_API_KEY is not set.
"""
import asyncio
import logging
import os
import re
import sys
import time
import uuid
from pathlib import Path
from typing import Dict, Any, Optional, List

from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect, UploadFile, File, Form, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from research_agent.agents.literature_review_agent import LiteratureReviewAgent
from research_agent.agents.data_processing_agent import DataProcessingAgent
from research_agent.agents.knowledge_graph_agent import KnowledgeGraphAgent
from research_agent.agents.analysis_agent import AnalysisAgent
from research_agent.agents.writing_assistant_agent import WritingAssistantAgent
from research_agent.agents.collaboration_agent import CollaborationAgent
from research_agent.api.document_store import store

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ── Groq client (optional) ────────────────────────────────────────────────────
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
groq_client = None
if GROQ_API_KEY:
    try:
        from groq import Groq
        groq_client = Groq(api_key=GROQ_API_KEY)
        logger.info("✅ Groq LLM enabled")
    except Exception as e:
        logger.warning(f"Groq init failed: {e}")
else:
    logger.warning("⚠️  GROQ_API_KEY not set — using template fallback answers")

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Research Agent API",
    description="Multi-agent research assistant — answers grounded in your uploaded papers.",
    version="3.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Agent singletons ──────────────────────────────────────────────────────────
literature_agent    = LiteratureReviewAgent()
data_agent          = DataProcessingAgent()
kg_agent            = KnowledgeGraphAgent()
analysis_agent      = AnalysisAgent()
writing_agent       = WritingAssistantAgent()
collaboration_agent = CollaborationAgent()

AGENTS = {
    "LiteratureReviewAgent":  literature_agent,
    "DataProcessingAgent":    data_agent,
    "KnowledgeGraphAgent":    kg_agent,
    "AnalysisAgent":          analysis_agent,
    "WritingAssistantAgent":  writing_agent,
    "CollaborationAgent":     collaboration_agent,
}

# ── WebSocket manager ─────────────────────────────────────────────────────────
class ConnectionManager:
    def __init__(self):
        self.active: Dict[str, WebSocket] = {}

    async def connect(self, sid: str, ws: WebSocket):
        await ws.accept()
        self.active[sid] = ws

    def disconnect(self, sid: str):
        self.active.pop(sid, None)

    async def send(self, sid: str, data: Dict):
        ws = self.active.get(sid)
        if ws:
            try:
                await ws.send_json(data)
            except Exception:
                self.disconnect(sid)

manager = ConnectionManager()

# ── Pydantic models ───────────────────────────────────────────────────────────
class QueryRequest(BaseModel):
    query: str
    session_id: Optional[str] = None
    project_id: Optional[str] = None

class AgentActionRequest(BaseModel):
    agent: str
    action: str
    params: Dict[str, Any] = {}
    session_id: Optional[str] = None

class ProjectRequest(BaseModel):
    name: str
    description: str = ""
    team_members: List[str] = []
    token_budget: int = 100000

class CollaborateRequest(BaseModel):
    project_id: str
    action: str
    params: Dict[str, Any] = {}

# ── LLM Answer Generation ─────────────────────────────────────────────────────

def _build_context(query: str, chunks: List[Dict]) -> str:
    """Build a clean context string from the most relevant chunks."""
    if not chunks:
        full = store.full_text()
        return full[:8000] if full else ""

    # Use all top chunks joined — don't truncate sentences mid-way
    parts = []
    total = 0
    for ch in chunks[:6]:
        text = ch["text"].strip()
        if total + len(text) > 7000:
            break
        parts.append(text)
        total += len(text)
    return "\n\n".join(parts)


def _llm_answer(query: str, context_chunks: List[Dict]) -> str:
    """
    Generate an answer using Groq LLM, or fall back to extractive answer.
    """
    if not groq_client:
        return _extractive_answer(query, context_chunks)

    context_text = _build_context(query, context_chunks)
    if not context_text:
        return "⚠️ No documents uploaded yet. Please upload a research paper first."

    system_prompt = (
        "You are a helpful research assistant. The user has uploaded a research document "
        "and will ask questions about it. Your job is to answer clearly and simply.\n\n"
        "Rules:\n"
        "- Answer in plain, easy-to-understand English\n"
        "- Be direct — start with the answer, then add detail\n"
        "- Use bullet points when listing multiple items\n"
        "- Keep it concise but complete — aim for 3-6 sentences or bullet points\n"
        "- Only use information from the provided document text\n"
        "- If the document doesn't contain the answer, say so clearly\n"
        "- Never start with 'Based on the excerpts' or 'According to the document'"
    )

    user_prompt = (
        f"Document content:\n\n{context_text}\n\n"
        f"Question: {query}\n\n"
        "Answer (simple and clear):"
    )

    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            temperature=0.2,
            max_tokens=800,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        logger.error(f"Groq API error: {e}")
        return _extractive_answer(query, context_chunks)


def _extractive_answer(query: str, chunks: List[Dict]) -> str:
    """
    Fallback: extract and present the most relevant sentences from the paper
    in a clean, readable way — even without an LLM.
    """
    if store.is_empty:
        return "⚠️ No documents uploaded yet. Please upload a research paper first."

    doc_name = next(iter(store._docs.values()), {}).get("filename", "uploaded document")

    # Get top relevant sentences
    sentences = store.search_sentences(query, top_k=8)
    entities  = store.all_entities()
    q_lower   = query.lower()

    lines: List[str] = []

    # ── Knowledge graph question ─────────────────────────────────────────────
    if any(w in q_lower for w in ["knowledge graph", "entities", "relations", "graph"]):
        methods  = [e["name"] for e in entities if e["type"] == "method"][:12]
        concepts = [e["name"] for e in entities if e["type"] == "concept"][:8]
        authors  = [e["name"] for e in entities if e["type"] == "author"][:6]
        relations = store.all_relations()[:10]

        lines.append(f"**Knowledge Graph — {doc_name}**\n")
        if methods:
            lines.append("**Methods & Models:**")
            lines.extend(f"- {m}" for m in methods)
        if concepts:
            lines.append(f"\n**Key Concepts:** {', '.join(concepts)}")
        if authors:
            years = [e["name"] for e in entities if e["type"] == "year"]
            lines.append("\n**Authors:**")
            for i, a in enumerate(authors):
                yr = years[i] if i < len(years) else ""
                lines.append(f"- {a}" + (f" ({yr})" if yr else ""))
        if relations:
            lines.append("\n**Connections:**")
            for r in relations[:6]:
                lines.append(f"- {r['source']} → {r['target']}")
        return "\n".join(lines)

    # ── General question: show relevant sentences ────────────────────────────
    lines.append(f"**From the paper: *{doc_name}***\n")

    if sentences:
        lines.append("Here is what the paper says about this:\n")
        for s in sentences[:6]:
            # Clean up the sentence
            text = s["text"].strip()
            text = re.sub(r"\s+", " ", text)
            lines.append(f"• {text}")
    else:
        # No strong keyword match — show opening of the paper
        all_chunks = store.all_chunks()
        if all_chunks:
            intro = all_chunks[0]["text"][:800].strip()
            intro = re.sub(r"\s+", " ", intro)
            lines.append(f"{intro}")
        else:
            lines.append("The document has been uploaded but could not be read properly.")

    # Add a note about configuring LLM for better answers
    lines.append(f"\n---\n_For more natural AI-generated answers, add your `GROQ_API_KEY` to `e:\\pcl\\research_agent\\.env`_")

    return "\n".join(lines)



def _build_citations(entities: List[Dict]) -> List[str]:
    authors = [e["name"] for e in entities if e["type"] == "author"]
    years   = [e["name"] for e in entities if e["type"] == "year"]
    return [f"{a} ({years[i] if i < len(years) else 'n.d.'})" for i, a in enumerate(authors[:6])]


def _sources_from_chunks(chunks: List[Dict]) -> List[Dict]:
    sources, seen = [], set()
    for ch in chunks[:5]:
        doc_id = ch["doc_id"]
        if doc_id in seen:
            continue
        seen.add(doc_id)
        doc = store.get_document(doc_id) or {}
        ents = doc.get("entities", [])
        authors = [e["name"] for e in ents if e["type"] == "author"][:3]
        years   = [e["name"] for e in ents if e["type"] == "year"]
        sources.append({
            "title":           ch["filename"],
            "authors":         authors or ["Uploaded Document"],
            "year":            int(years[0]) if years else 2024,
            "venue":           "Uploaded Document",
            "relevance_score": ch.get("relevance_score", 0.9),
            "excerpt":         ch["text"][:200],
        })
    return sources

# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
async def root():
    return {
        "service": "Research Agent API", "version": "3.0.0",
        "llm_enabled": groq_client is not None,
        "documents_indexed": store.doc_count,
        "agents": list(AGENTS.keys()), "status": "online",
    }

@app.get("/api/health")
async def health():
    return {
        "status": "healthy",
        "llm_enabled": groq_client is not None,
        "agents": {n: a.status for n, a in AGENTS.items()},
        "documents_indexed": store.doc_count,
        "timestamp": time.time(),
    }

@app.get("/api/agents")
async def get_agents():
    return {
        "agents": [{"name": n, "description": a.description, "status": a.status} for n, a in AGENTS.items()],
        "count": len(AGENTS),
    }

# ── Upload ─────────────────────────────────────────────────────────────────────

@app.post("/api/upload")
async def upload_document(file: UploadFile = File(...), session_id: str = Form(default="")):
    sid = session_id or str(uuid.uuid4())
    try:
        raw = await file.read()
        doc_id = f"doc_{uuid.uuid4().hex[:8]}"

        await manager.send(sid, {"type": "upload_started", "file_name": file.filename, "agent": "DataProcessingAgent"})

        result = store.add_document(doc_id, file.filename, raw)

        await manager.send(sid, {"type": "agent_step", "agent": "DataProcessingAgent", "step": "chunk", "progress": 60, "result": result})
        await manager.send(sid, {"type": "agent_step", "agent": "KnowledgeGraphAgent", "step": "extract_knowledge", "progress": 100, "result": result})
        await manager.send(sid, {"type": "upload_complete", **result})

        return {
            "status": "success", "file_name": file.filename, "doc_id": doc_id,
            "file_size": len(raw), "chunks": result["num_chunks"],
            "entities": result["entities_extracted"], "relations": result["relations_extracted"],
            "word_count": result["word_count"], "session_id": sid,
            "llm_ready": groq_client is not None,
            "message": f"'{file.filename}' indexed — {result['word_count']:,} words in {result['num_chunks']} chunks",
        }
    except Exception as e:
        logger.error(f"Upload error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))

# ── Query Pipeline ─────────────────────────────────────────────────────────────

@app.post("/api/query")
async def research_query(request: QueryRequest):
    """Run the full 6-agent research pipeline. Answers come from the real uploaded paper via LLM."""
    sid   = request.session_id or str(uuid.uuid4())
    query = request.query.strip()

    try:
        # ── Step 1-2: Retrieve relevant chunks ──
        await manager.send(sid, {"type": "agent_active", "agent": "LiteratureReviewAgent"})
        matched_chunks = store.search(query, top_k=8)
        await manager.send(sid, {"type": "agent_step", "agent": "LiteratureReviewAgent", "progress": 20})

        # ── Step 3: Knowledge graph ──
        await manager.send(sid, {"type": "agent_active", "agent": "DataProcessingAgent"})
        await manager.send(sid, {"type": "agent_step", "agent": "DataProcessingAgent", "progress": 38})

        await manager.send(sid, {"type": "agent_active", "agent": "KnowledgeGraphAgent"})
        entities  = store.all_entities()
        relations = store.all_relations()
        await manager.send(sid, {"type": "agent_step", "agent": "KnowledgeGraphAgent", "progress": 58})

        # ── Step 4: Analysis ──
        await manager.send(sid, {"type": "agent_active", "agent": "AnalysisAgent"})
        await manager.send(sid, {"type": "agent_step", "agent": "AnalysisAgent", "progress": 74})

        # ── Step 5: Generate answer via LLM ──
        await manager.send(sid, {"type": "agent_active", "agent": "WritingAssistantAgent"})
        # Run LLM call in thread so it doesn't block the event loop
        answer = await asyncio.get_event_loop().run_in_executor(
            None, _llm_answer, query, matched_chunks
        )
        await manager.send(sid, {"type": "agent_step", "agent": "WritingAssistantAgent", "progress": 92})

        # ── Step 6: Log ──
        await collaboration_agent.execute({
            "action": "log_action", "action_type": "research_query",
            "agent": "Pipeline", "details": {"query": query, "session_id": sid},
        })
        await manager.send(sid, {"type": "pipeline_complete", "progress": 100})

        sources   = _sources_from_chunks(matched_chunks)
        citations = _build_citations(entities)

        return {
            "status": "success", "query": query, "answer": answer,
            "citations": citations,
            "confidence": round(0.75 + min(len(matched_chunks) * 0.025, 0.2), 2),
            "sources": sources,
            "agent_steps": [
                {"agent": "LiteratureReviewAgent", "action": "retrieve_chunks", "status": "completed"},
                {"agent": "DataProcessingAgent",   "action": "filter",          "status": "completed"},
                {"agent": "KnowledgeGraphAgent",   "action": "query_graph",     "status": "completed"},
                {"agent": "AnalysisAgent",         "action": "analyze_trends",  "status": "completed"},
                {"agent": "WritingAssistantAgent", "action": "generate_answer", "status": "completed"},
                {"agent": "CollaborationAgent",    "action": "log_action",      "status": "completed"},
            ],
            "pipeline_used": list(AGENTS.keys()),
            "llm_used": groq_client is not None,
            "session_id": sid,
        }

    except Exception as e:
        logger.error(f"Query error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))

# ── Individual agent ──────────────────────────────────────────────────────────

@app.post("/api/agent/execute")
async def execute_agent(request: AgentActionRequest):
    if request.agent not in AGENTS:
        raise HTTPException(status_code=404, detail=f"Agent '{request.agent}' not found")
    result = await AGENTS[request.agent].execute({"action": request.action, **request.params})
    if request.session_id:
        await manager.send(request.session_id, {"type": "agent_result", "agent": request.agent, "result": result})
    return result

@app.get("/api/agent/{agent_name}/status")
async def agent_status(agent_name: str):
    if agent_name not in AGENTS:
        raise HTTPException(status_code=404)
    a = AGENTS[agent_name]
    return {"agent": agent_name, "status": a.status, "description": a.description}

# ── Knowledge Graph ───────────────────────────────────────────────────────────

@app.get("/api/knowledge-graph/entities")
async def kg_entities():
    e = store.all_entities()
    return {"entities": e, "count": len(e), "documents_indexed": store.doc_count}

@app.get("/api/knowledge-graph/relations")
async def kg_relations():
    r = store.all_relations()
    return {"relations": r, "count": len(r)}

@app.post("/api/knowledge-graph/query")
async def kg_query(query: str = Query(...), top_k: int = Query(default=5)):
    return {"query": query, "chunks": store.search(query, top_k), "entities": store.all_entities()[:20], "relations": store.all_relations()[:20]}

# ── Analysis ──────────────────────────────────────────────────────────────────

@app.get("/api/analysis/trends")
async def analysis_trends(topic: str = Query(default="")):
    ents  = store.all_entities()
    years = sorted(set(e["name"] for e in ents if e["type"] == "year"))
    meths = [e["name"] for e in ents if e["type"] == "method"][:10]
    return {"topic": topic, "years_detected": years, "methods": meths, "documents": store.doc_count}

@app.get("/api/analysis/citation-network")
async def citation_network():
    ents = store.all_entities()
    return {"nodes": [e for e in ents if e["type"] == "author"][:20], "edges": store.all_relations()[:20]}

@app.get("/api/analysis/research-gaps")
async def research_gaps(topic: str = Query(default="")):
    return {"topic": topic, "documents": store.doc_count}

# ── Collaboration ─────────────────────────────────────────────────────────────

@app.post("/api/projects")
async def create_project(request: ProjectRequest):
    return await collaboration_agent.execute({
        "action": "create_project", "name": request.name,
        "description": request.description, "team_members": request.team_members,
        "token_budget": request.token_budget,
    })

@app.post("/api/projects/{project_id}/collaborate")
async def collaborate(project_id: str, request: CollaborateRequest):
    return await collaboration_agent.execute({"action": request.action, "project_id": project_id, **request.params})

@app.get("/api/projects/{project_id}")
async def get_project(project_id: str):
    return await collaboration_agent.execute({"action": "get_project", "project_id": project_id})

# ── WebSocket ─────────────────────────────────────────────────────────────────

@app.websocket("/ws/{session_id}")
async def websocket_endpoint(websocket: WebSocket, session_id: str):
    await manager.connect(session_id, websocket)
    try:
        await websocket.send_json({
            "type": "connected", "session_id": session_id,
            "agents": list(AGENTS.keys()), "llm_enabled": groq_client is not None,
        })
        while True:
            try:
                data = await asyncio.wait_for(websocket.receive_json(), timeout=30.0)
                if data.get("type") == "ping":
                    await websocket.send_json({"type": "pong"})
            except asyncio.TimeoutError:
                await websocket.send_json({"type": "heartbeat", "timestamp": time.time()})
    except WebSocketDisconnect:
        manager.disconnect(session_id)
    except Exception as e:
        logger.error(f"WS error {session_id}: {e}")
        manager.disconnect(session_id)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=8000, reload=True)
